### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by DavidAwing** [RainManGO/3d-earth#1]
[webpack-cli] Failed to load 'D:\temp\3DEARTH\3d-earth-main2\webpack.config.js' config
[webpack-cli] Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- D:\temp\3DEARTH\3d-earth-main2\node_modules\ajv-keywords\dist\definitions\typeof.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\ajv-keywords\dist\keywords\typeof.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\ajv-keywords\dist\keywords\index.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\ajv-keywords\dist\index.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\schema-utils\dist\validate.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\schema-utils\dist\index.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\mini-css-extract-plugin\dist\index.js
- D:\temp\3DEARTH\3d-earth-main2\webpack.config.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\webpack-cli\lib\webpack-cli.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\webpack-cli\lib\bootstrap.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\webpack-cli\bin\cli.js
- D:\temp\3DEARTH\3d-earth-main2\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\temp\3DEARTH\3d-earth-main2\node_modules\ajv-keywords\dist\definitions\typeof.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\ajv-keywords\\dist\\definitions\\typeof.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\ajv-keywords\\dist\\keywords\\typeof.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\ajv-keywords\\dist\\keywords\\index.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\ajv-keywords\\dist\\index.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\schema-utils\\dist\\validate.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\schema-utils\\dist\\index.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\mini-css-extract-plugin\\dist\\index.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\webpack.config.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\webpack-cli\\bin\\cli.js',
    'D:\\temp\\3DEARTH\\3d-earth-main2\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! 3d-earth@1.0.5 build: `webpack --mode=production --node-env=production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the 3d-earth@1.0.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wing\AppData\Roaming\npm-cache\_logs\2022-04-10T09_20_15_573Z-debug.log

**Comment by DavidAwing** [comment]
Compiled successfully after adding dependencies to package.json :    devDependencies=> "ajv": "^7.0.3"
